### ISSUE TITLE
[Regression] cgo linking error with rules_go 0.58

### ISSUE THREAD

**Issue by mering** [bazel-contrib/rules_go#4548]
When depending on the same dynamic library via `cgo` and via `go-cgo`, we get duplicate symbol errors starting form 0.58 while things worked fine in 0.57. You can find a reproduction example in https://github.com/mering/reproduction_rules_go_0_59.

Excerpt from the `BUILD` file:
```starlark
cc_library(
    name = "world",
    deps = [
        "@abseil-cpp//absl/log:flags",
    ],
)

go_library(
    name = "world_go",
    srcs = ["world.go"],
    cdeps = [":world"],
    cgo = 1,
)

go_test(
    name = "world_go_test",
    srcs = ["world_go_test.go"],
    cdeps = [":world"],
    cgo = 1,
    deps = [
        ":world_go",
    ],
)
```

**Comment by fmeum** [comment]
Could you run a bisect to determine the breaking commit?

**Comment by mering** [comment]
> Could you run a bisect to determine the breaking commit?

I already did, just forgot to link it in the description. The first bad commit is 20f7e2bb45dfbd6630f7ce36ad62cb9001a7e2f5.

**Comment by fmeum** [comment]
@enscogitans in case you have an idea.

**Comment by enscogitans** [comment]
Interestingly, my PR introduced a similar test case, and it works.

In the original PR I had issues with duplicated symbols too. I solved the problem by filtering out any repeating `.lo` libs (see `seen_alwayslink_libs`)

https://github.com/bazel-contrib/rules_go/blob/ebd809f18f9d25b332463638ff50160bbbea83c7/go/private/rules/cgo.bzl#L150-L154

My hypothesis is that current problem is caused by some library that appeared twice. First time it was added as an always link library on the line 152. And the second time as a usual library on the line 154.

If this is the case, one will have to read all libraries first, and only after that they will have to decide for each library whether it should be processed as an alwayslink or not

**Comment by mering** [comment]
@fmeum Can you revert the breaking commit in order to mitigate the regression until a properly fixed version of the feature is available?

**Comment by fmeum** [comment]
Sent a revert in https://github.com/bazel-contrib/rules_go/pull/4551.

@dzbarsky Let's include this in the release
